title: Adrian Guerra

# permalink: /:slug

plugins:
  - jekyll-bookshop
  - cloudcannon-jekyll-bookshop
  - jekyll-sitemap
  # - jekyll/tagging
  - jekyll-pagebreak

# Multiple bookshops can be used on one website,
# or different production / staging locations.
bookshop_locations:
  - ../components

exclude:
  - postcss.config.js
  - node_modules

include:
  - _cloudcannon

# The rest of this array structure will be
# populated by the bookshop-array-structures plugin.
_array_structures:
  content_blocks:
    style: modal

language_default: en

collections_dir: 'collections'

collections:
  en:
    output: true
    permalink: /:slug
  fr:
    output: true
    permalink: /:collection/:slug
  es:
    output: true
    permalink: /:collection/:slug
  
cloudcannon:
  collections:
    pages:
      _icon: 'wysiwyg'
    projects:
      _icon: 'work_outline'
      _subtext_key: subtitle
    testimonials:
      _icon: 'format_quote'
      _subtext_key: position
      _enabled_editors:
        - data

_collection_groups:
  - heading: Content
    collections:
      - pages
      - projects
      - testimonials
  - heading: Blogging
    collections:
      - posts
      - drafts
  - heading: Settings
    collections:
      - data

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: pages
      path: _en/pages/index.html
    values:
      permalink: /
  - scope:
      path: _en/projects
    values:
      layout: project
      permalink: /portfolio/:slug
  - scope:
      path: _en/posts
    values:
      layout: post
      permalink: /blog/:slug

  - scope:
      type: pages
      path: _fr/pages/index.html
    values:
      permalink: /
  - scope:
      path: _fr/projects
    values:
      layout: project
      permalink: /fr/portfolio/:slug
  - scope:
      path: _fr/posts
    values:
      layout: post
      permalink: /fr/blog/:slug

  - scope:
      type: pages
      path: _es/pages/index.html
    values:
      permalink: /
  - scope:
      path: _es/projects
    values:
      layout: project
      permalink: /es/portfolio/:slug
  - scope:
      path: _es/posts
    values:
      layout: post
      permalink: /es/blog/:slug
