title: Adrian Guerra | Marketing Scientist
description: Unlock growth by extracting value from your data with Adrian Guerra - Marketing Scientist
social_media_share_image: /images/AG.jpg
disqus-identifier:
google-analytics: G-YDKXV85N7Q
author: '{{ site.data.author.author_name }}'
author_url: '{{ site.data.author.author_url }}'